Update playbook.yaml

diff --git a/playbook.yaml b/playbook.yaml
--- a/playbook.yaml
+++ b/playbook.yaml
@@ -3,18 +3,30 @@
   tasks:
   - name: pinging hosts
     ansible.builtin.ping:
-
-  - name: Print message
-    ansible.builtin.debug:
-      msg: Hello World
-
-  - name: checking disk space
-    ansible.builtin.shell: df
-    register: disk_usage
-
+    
   - name: Display Output
     ansible.builtin.debug:
       var: disk_usage.stdout_lines
+
+  - name: Backup old files
+    ansible.builtin.shell: |
+      cd /home/ubuntu/Dummy-Website
+      if [ ! -s testing-maingo-bak ]; then
+        echo "Backup file is empty or does not exist. Skipping delete old backup process."
+      else
+        rm testing-maingo-bak
+      fi
+
+      if [ ! -s testing-maingo ]; then
+        echo "Backup file is empty or does not exist. Skipping backup process."
+      else
+        mv testing-maingo testing-maingo-bak
+          if [ $? -eq 0 ]; then
+            echo "File renamed successfully"
+          else
+            echo "Rename failed."
+          fi
+      fi
 
   - name: Cloning Git
     ansible.builtin.shell: |
@@ -23,19 +35,20 @@
       go mod init mango
       go mod tidy
       CGO_ENABLED=0 GOOS=linux go build -o testing-maingo
-    register: build_logs
 
-  - name: Display Build Log
-    ansible.builtin.debug:
-      var: build_logs.stdout_lines
-
+  - name: Kill old process
+    ansible.builtin.shell: |
+      PIDS=\$(pidof testing-maingo)
+      if [ -n "\$PIDS" ]; then
+        sudo kill -9 \$PIDS
+        echo "Process 'testing-maingo' terminated."
+      else
+        echo "No process found for 'testing-maingo'."
+      fi
+      
   - name: Running Service with nohup
     ansible.builtin.shell: |
       cd /home/ubuntu/Dummy-Website
       nohup ./testing-maingo > nohup.out 2>&1 &
       tail nohup.out
     register: deploy_logs
-
-  - name: display Deploy Log
-    ansible.builtin.debug:
-      var: deploy_logs.stdout_lines
